version: "3.8"

services:
  app:
    build: .
    container_name: spark-cluster
    environment:
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - AZURE_BLOB_CONTAINER=${AZURE_BLOB_CONTAINER}
      - AZURE_BLOB_FILE=${AZURE_BLOB_FILE}
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - .env:/app/.env
    command: ["python3", "/app/src/main.py"]
    ports:
      - "8888:8888"

  tests:
    build: .
    container_name: spark-tests
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - .env:/app/.env
    command: ["pytest", "/app/tests"]
